app-config:
  server:
    port: 8080
  database:
    host:  localhost
    port : 5432
    dbname: ya-coding
    username: postgres
    #     local
    password: 1234


  auth:
    audience: "yc-test-platform-user"
    issuer: "yc-test-platform"
    secret-key: "a-very-secret-key"
    algorithm: "HS256"

spring:
  profiles:
    active: dev
#    active: test
  jpa:
    show-sql: "${app-config.database.debug:false}"