app-config:
  server:
    port: 8080
  database:
    host:  localhost
    port : 5432
    dbname: ya-coding
    username: postgres
    #     local
    password: 1234

spring:
  profiles:
    active: dev
#    active: test
  jpa:
    show-sql: "${app-config.database.debug:false}"