app-config:
  server:
    port: 8443
  database:
    host:  localhost
    port : 5432
    dbname: postgres
    username: postgres
    #     local
    password: 1234

spring:
  profiles:
    active: dev
#    active: test
  jpa:
    show-sql: "${app-config.database.debug:false}"