server:
  port: "8080"

logging:
  level:
    root: INFO

spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: true
    change-log: "classpath:db.changelog-master.yaml"
  datasource:
    url: "jdbc:postgresql://${app-config.database.host}:${app-config.database.port}/${app-config.database.dbname}"
    username: "${app-config.database.username}"
    password: "${app-config.database.password}"
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: "${app-config.database.debug:false}"
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        metadata_builder_contributor: ru.yescoding.app.repository.CustomSQLFunctionsRegistrar
        use_jdbc_metadata_defaults: false
